name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - develop
      - main

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting
        run: dotnet format --verify-no-changes
